apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /dev/fd/2;

    events {
      worker_connections 1024;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /dev/fd/1 main;

      server {
        listen 80;
        server_name _;

        location / {
          root html;
          index index.html index.htm;
        }
      }

      include /etc/nginx/conf.d/*.conf;
    }
